export enum CLIENT_ROUTES {
  MAIN = '/',
  ALLTRENER = '/alltraner',
  ALLCLIENTS = '/allclients',
  CATALOGEXERCISE = '/catalogexercise',
  BOOKS = '/books',
  ADDBOOK = '/addbook',
  LOGIN = '/login',
  SIGN_UP = '/signup',
  PROFILE = '/profile',
  EDITING = '/editing',
  ABOUT = '/about',
  NOT_FOUND = '*',
  SIGN_UP_TRENER = '/signuptrener',
  CALENDAR = '/calendar',
  CHAT = '/chat',
  TRAINING = '/training/:trainingId',
}
